// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using USMB_TECH.Models.EntityFramework;

#nullable disable

namespace USMB_TECH.Migrations
{
    [DbContext(typeof(UsmbTechDbContext))]
    partial class UsmbTechDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("usmbTech")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("USMB_TECH.Models.Adresse", b =>
                {
                    b.Property<int>("Id_Adresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_adresse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Adresse"));

                    b.Property<string>("Code_Postal_Adresse")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("code_postal_adresse");

                    b.Property<string>("Complement_Rue_Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("complement_rue_adresse");

                    b.Property<string>("Pays_Adresse")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pays_adresse");

                    b.Property<string>("Rue_Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rue_adresse");

                    b.Property<string>("Ville_Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ville_adresse");

                    b.HasKey("Id_Adresse")
                        .HasName("pk_adresse");

                    b.ToTable("adresse", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Associer", b =>
                {
                    b.Property<int>("Id_Contact")
                        .HasColumnType("integer")
                        .HasColumnName("id_contact");

                    b.Property<int>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.Property<string>("Fonction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fonction");

                    b.HasKey("Id_Contact", "Id_Pole_Expertise")
                        .HasName("pk_associer");

                    b.HasIndex("Id_Pole_Expertise");

                    b.ToTable("associer", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Consommable", b =>
                {
                    b.Property<int>("Id_Consommable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consommable");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Consommable"));

                    b.Property<bool>("Forfait")
                        .HasColumnType("boolean")
                        .HasColumnName("forfait");

                    b.Property<int>("Id_Unite")
                        .HasColumnType("integer")
                        .HasColumnName("id_unite");

                    b.Property<string>("Nom_Consommable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_consommable");

                    b.Property<double>("Prix_Forfait")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("prix_forfait");

                    b.Property<double>("Prix_Unite")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("prix_unite");

                    b.HasKey("Id_Consommable")
                        .HasName("pk_consommable");

                    b.HasIndex("Id_Unite");

                    b.ToTable("consommable", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Consommer", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int>("Id_Consommable")
                        .HasColumnType("integer")
                        .HasColumnName("id_consommable");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Id_Equipement", "Id_Consommable")
                        .HasName("pk_consommer");

                    b.HasIndex("Id_Consommable");

                    b.ToTable("consommer", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Contact_USMB", b =>
                {
                    b.Property<int>("Id_Contact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Contact");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Contact"));

                    b.Property<string>("Code_RH")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("code_rh");

                    b.Property<int>("Id_Fonction")
                        .HasColumnType("integer")
                        .HasColumnName("id_fonction");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mail");

                    b.Property<string>("Nom_Contact")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_contact");

                    b.Property<string>("Nom_Court")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_court");

                    b.Property<string>("Num_Securite_Social")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("num_securite_social");

                    b.Property<string>("Prenom_Contact")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenom_contact");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telephone");

                    b.HasKey("Id_Contact")
                        .HasName("pk_contact_USMB");

                    b.HasIndex("Id_Fonction");

                    b.HasIndex("Nom_Court");

                    b.ToTable("contact_usmb", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Designer", b =>
                {
                    b.Property<int>("Id_Mot_Clef")
                        .HasColumnType("integer")
                        .HasColumnName("id_mot_clef");

                    b.Property<string>("Nom_Court")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_court");

                    b.HasKey("Id_Mot_Clef", "Nom_Court")
                        .HasName("pk_designer");

                    b.HasIndex("Nom_Court");

                    b.ToTable("designer", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Domaine_Excellence", b =>
                {
                    b.Property<int>("Id_Domaine_Excellence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_domaine_excellence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Domaine_Excellence"));

                    b.Property<string>("Description_Domaine_Excellence")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description_domaine_excellence");

                    b.Property<string>("intitule_Domaine_Excellence")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("intitule_domaine_excellence");

                    b.HasKey("Id_Domaine_Excellence")
                        .HasName("pk_domaine_excellence");

                    b.ToTable("domaine_excellence", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Equipement", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Equipement"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.Property<bool>("Autonomie")
                        .HasColumnType("boolean")
                        .HasColumnName("autonomie");

                    b.Property<DateTime>("Date_Acquisition")
                        .HasColumnType("date")
                        .HasColumnName("date_acquisition");

                    b.Property<string>("Description_Technique")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_technique");

                    b.Property<bool>("Disponibilite")
                        .HasColumnType("boolean")
                        .HasColumnName("disponibilite");

                    b.Property<int>("Id_Modele")
                        .HasColumnType("integer")
                        .HasColumnName("id_modele");

                    b.Property<int>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.Property<int>("Id_Type_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_equipement");

                    b.Property<string>("Nom_Equipement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_equipement");

                    b.Property<string>("Num_Immobilisation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("num_immobilisation");

                    b.Property<double>("Prix_Achat")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("prix_achat");

                    b.Property<double>("Prix_Revient")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("prix_revient");

                    b.Property<bool>("Utilisable_Chez_Le_Client")
                        .HasColumnType("boolean")
                        .HasColumnName("utilisable_chez_le_client");

                    b.HasKey("Id_Equipement")
                        .HasName("pk_equipement");

                    b.HasIndex("Id_Modele");

                    b.HasIndex("Id_Pole_Expertise");

                    b.HasIndex("Id_Type_Equipement");

                    b.ToTable("equipement", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Est_Lier", b =>
                {
                    b.Property<string>("Nom_Court")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_court");

                    b.Property<int>("Id_Thematique")
                        .HasColumnType("integer")
                        .HasColumnName("id_thematique");

                    b.HasKey("Nom_Court", "Id_Thematique")
                        .HasName("pk_est_lier");

                    b.HasIndex("Id_Thematique");

                    b.ToTable("est_lier", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Exemple_Utilisation", b =>
                {
                    b.Property<int>("Id_Exemple_Utilisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_exemple_utilisation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Exemple_Utilisation"));

                    b.Property<string>("Description_Utilisation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_utilisation");

                    b.Property<int?>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int?>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.Property<string>("Nom_Utilisation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_utilisation");

                    b.HasKey("Id_Exemple_Utilisation")
                        .HasName("pk_exemple_utilisation");

                    b.HasIndex("Id_Equipement");

                    b.HasIndex("Id_Pole_Expertise");

                    b.ToTable("exemple_utilisation", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Exposer", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int>("Id_Thematique")
                        .HasColumnType("integer")
                        .HasColumnName("id_thematique");

                    b.Property<int?>("Id_Pole_Expertise")
                        .HasColumnType("integer");

                    b.HasKey("Id_Equipement", "Id_Thematique")
                        .HasName("pk_exposer");

                    b.HasIndex("Id_Thematique");

                    b.ToTable("exposer", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Fonction", b =>
                {
                    b.Property<int>("Id_Fonction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fonction");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Fonction"));

                    b.Property<string>("Nom_Fonction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_fonction");

                    b.HasKey("Id_Fonction")
                        .HasName("pk_fonction");

                    b.ToTable("fonction", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Fonctionalite", b =>
                {
                    b.Property<int>("Id_Fonctionalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fonctionalite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Fonctionalite"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Nom_Fonctionalite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_fonctionalite");

                    b.HasKey("Id_Fonctionalite")
                        .HasName("pk_fonctionalite");

                    b.ToTable("fonctionalite", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Fournir", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int>("Id_Prestation")
                        .HasColumnType("integer")
                        .HasColumnName("id_prestation");

                    b.HasKey("Id_Equipement", "Id_Prestation")
                        .HasName("pk_fournir");

                    b.HasIndex("Id_Prestation");

                    b.ToTable("fournir", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Gerer", b =>
                {
                    b.Property<int>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.Property<string>("Nom_Court")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_court");

                    b.Property<double>("Pourcentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("pourcentage");

                    b.HasKey("Id_Pole_Expertise", "Nom_Court")
                        .HasName("pk_gerer");

                    b.HasIndex("Nom_Court");

                    b.ToTable("gerer", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Laboratoire", b =>
                {
                    b.Property<string>("Nom_Court")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_court");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Id_Adresse_Campus")
                        .HasColumnType("integer")
                        .HasColumnName("id_adresse_campus");

                    b.Property<int>("Id_Adresse_Labo")
                        .HasColumnType("integer")
                        .HasColumnName("id_adresse_labo");

                    b.Property<string>("Nom_Long")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nom_long");

                    b.HasKey("Nom_Court")
                        .HasName("pk_laboratoire");

                    b.HasIndex("Id_Adresse_Campus");

                    b.HasIndex("Id_Adresse_Labo");

                    b.ToTable("laboratoire", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Marque", b =>
                {
                    b.Property<int>("Id_Marque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_marque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Marque"));

                    b.Property<string>("Nom_Marque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_marque");

                    b.HasKey("Id_Marque")
                        .HasName("pk_marque");

                    b.ToTable("marque", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Modele", b =>
                {
                    b.Property<int>("Id_Modele")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_modele");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Modele"));

                    b.Property<int>("Id_Marque")
                        .HasColumnType("integer")
                        .HasColumnName("id_marque");

                    b.Property<string>("Nom_Modele")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_modele");

                    b.HasKey("Id_Modele")
                        .HasName("pk_modele");

                    b.HasIndex("Id_Marque");

                    b.ToTable("modele", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Mot_Clef", b =>
                {
                    b.Property<int>("Id_Mot_Clef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mot_clef");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Mot_Clef"));

                    b.Property<string>("Nom_Mot_Clef")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_mot_clef");

                    b.HasKey("Id_Mot_Clef")
                        .HasName("pk_mot_clef");

                    b.ToTable("mot_clef", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Photo", b =>
                {
                    b.Property<int>("Id_Photo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_photo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Photo"));

                    b.Property<int?>("Id_Domaine_Excellence")
                        .HasColumnType("integer")
                        .HasColumnName("id_domaine_excellence");

                    b.Property<int?>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int?>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.Property<int?>("Id_Prestation")
                        .HasColumnType("integer")
                        .HasColumnName("id_prestation");

                    b.Property<string>("Nom_Court")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_court");

                    b.Property<string>("Nom_Photo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom_photo");

                    b.Property<string>("Url_Photo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_photo");

                    b.HasKey("Id_Photo")
                        .HasName("pk_photo");

                    b.HasIndex("Id_Domaine_Excellence");

                    b.HasIndex("Id_Equipement");

                    b.HasIndex("Id_Pole_Expertise");

                    b.HasIndex("Id_Prestation");

                    b.HasIndex("Nom_Court");

                    b.ToTable("photo", "usmbTech", t =>
                        {
                            t.HasCheckConstraint("CK_Photo_EquipementOuPole_ExpertiseOuDomaine_Excellence", "(\r\n                        ((id_equipement IS NOT NULL)::int +\r\n                        (id_pole_expertise IS NOT NULL)::int +\r\n                        (id_prestation IS NOT NULL)::int +\r\n                        (nom_court IS NOT NULL)::int +\r\n                        (id_domaine_excellence IS NOT NULL)::int)\r\n                    ) = 1");
                        });
                });

            modelBuilder.Entity("USMB_TECH.Models.Pole_Expertise", b =>
                {
                    b.Property<int>("Id_Pole_Expertise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pole_Expertise"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.Property<string>("Description_Contenu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_contenu");

                    b.Property<string>("Description_Pole_Expertise")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description_pole_expertise");

                    b.Property<int>("Id_Domaine_Excellence")
                        .HasColumnType("integer")
                        .HasColumnName("id_domaine_excellence");

                    b.Property<string>("Nom_Contenu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_contenu");

                    b.Property<string>("Nom_Pole_Expertise")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_pole_expertise");

                    b.Property<string>("Url_Contenu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("url_contenu");

                    b.HasKey("Id_Pole_Expertise")
                        .HasName("pk_pole_expertise");

                    b.HasIndex("Id_Domaine_Excellence");

                    b.ToTable("pole_expertise", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Posseder", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int>("Id_Fonctionalite")
                        .HasColumnType("integer")
                        .HasColumnName("id_fonctionalite");

                    b.HasKey("Id_Equipement", "Id_Fonctionalite")
                        .HasName("pk_posseder");

                    b.HasIndex("Id_Fonctionalite");

                    b.ToTable("posseder", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Preciser", b =>
                {
                    b.Property<int>("Id_Prestation")
                        .HasColumnType("integer")
                        .HasColumnName("id_prestation");

                    b.Property<int>("Id_Mot_Clef")
                        .HasColumnType("integer")
                        .HasColumnName("id_mot_clef");

                    b.HasKey("Id_Prestation", "Id_Mot_Clef")
                        .HasName("pk_preciser");

                    b.HasIndex("Id_Mot_Clef");

                    b.ToTable("preciser", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Presenter", b =>
                {
                    b.Property<int>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.Property<int>("Id_Prestation")
                        .HasColumnType("integer")
                        .HasColumnName("id_prestation");

                    b.HasKey("Id_Pole_Expertise", "Id_Prestation")
                        .HasName("pk_presenter");

                    b.HasIndex("Id_Prestation");

                    b.ToTable("presenter", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Prestation", b =>
                {
                    b.Property<int>("Id_Prestation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_prestation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Prestation"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean")
                        .HasColumnName("actif");

                    b.Property<string>("Description_Prestation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_prestation");

                    b.Property<int>("Id_Contact")
                        .HasColumnType("integer")
                        .HasColumnName("id_contact");

                    b.Property<int>("Id_Domaine_Excellence")
                        .HasColumnType("integer")
                        .HasColumnName("id_domaine_excellence");

                    b.Property<int>("Id_Type_Prestation")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_prestation");

                    b.Property<int>("Id_Unite_Oeuvre")
                        .HasColumnType("integer")
                        .HasColumnName("id_unite_oeuvre");

                    b.Property<string>("Intitule_Prestation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("intitule_prestation");

                    b.Property<string>("Nom_Court")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nom_court");

                    b.Property<bool>("Peux_Ce_Realiser_Chez_Le_Client")
                        .HasColumnType("boolean")
                        .HasColumnName("peux_ce_realiser_chez_le_client");

                    b.Property<double>("Prix_Revient")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("prix_revient");

                    b.Property<double>("Prix_Vente")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("prix_vente");

                    b.HasKey("Id_Prestation")
                        .HasName("pk_prestation");

                    b.HasIndex("Id_Contact");

                    b.HasIndex("Id_Domaine_Excellence");

                    b.HasIndex("Id_Type_Prestation");

                    b.HasIndex("Id_Unite_Oeuvre");

                    b.HasIndex("Nom_Court");

                    b.ToTable("prestation", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Prise_Contact", b =>
                {
                    b.Property<int>("Num_Prise_Contact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("num_prise_contact");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Num_Prise_Contact"));

                    b.Property<string>("Description_besoins")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description_besoins");

                    b.Property<string>("Email_Contact")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("email_contact");

                    b.Property<string>("Entreprise_Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entreprise_contact");

                    b.Property<int?>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int?>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.Property<int>("Id_Type_Client")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_client");

                    b.Property<string>("Nom_Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_contact");

                    b.Property<string>("Prenom_Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenom_contact");

                    b.HasKey("Num_Prise_Contact")
                        .HasName("pk_prise_contact");

                    b.HasIndex("Id_Equipement");

                    b.HasIndex("Id_Pole_Expertise");

                    b.HasIndex("Id_Type_Client");

                    b.ToTable("prise_contact", "usmbTech", t =>
                        {
                            t.HasCheckConstraint("CK_PriseContact_EquipementOuPole_Expertise", "(\"id_equipement\" IS NULL) <> (\"id_pole_expertise\" IS NULL)");
                        });
                });

            modelBuilder.Entity("USMB_TECH.Models.Qualifier", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int>("Id_Mot_Clef")
                        .HasColumnType("integer")
                        .HasColumnName("id_mot_clef");

                    b.HasKey("Id_Equipement", "Id_Mot_Clef")
                        .HasName("pk_qualifier");

                    b.HasIndex("Id_Mot_Clef");

                    b.ToTable("qualifier", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Referencer", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .HasColumnType("integer")
                        .HasColumnName("id_equipement");

                    b.Property<int>("Id_Contact")
                        .HasColumnType("integer")
                        .HasColumnName("id_contact");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id_Equipement", "Id_Contact")
                        .HasName("pk_referencer");

                    b.HasIndex("Id_Contact");

                    b.ToTable("referencer", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Specifier", b =>
                {
                    b.Property<int>("Id_Mot_Clef")
                        .HasColumnType("integer")
                        .HasColumnName("id_mot_clef");

                    b.Property<int>("Id_Pole_Expertise")
                        .HasColumnType("integer")
                        .HasColumnName("id_pole_expertise");

                    b.HasKey("Id_Mot_Clef", "Id_Pole_Expertise")
                        .HasName("pk_specifier");

                    b.HasIndex("Id_Pole_Expertise");

                    b.ToTable("specifier", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Thematique", b =>
                {
                    b.Property<int>("Id_Thematique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_thematique");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Thematique"));

                    b.Property<int>("Id_Sous_Thematique")
                        .HasColumnType("integer")
                        .HasColumnName("id_sous_thematique");

                    b.Property<string>("Nom_Thematique")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_thematique");

                    b.HasKey("Id_Thematique")
                        .HasName("pk_thematique");

                    b.ToTable("thematique", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Type_Client", b =>
                {
                    b.Property<int>("Id_Type_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type_client");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Type_Client"));

                    b.Property<string>("Nom_Type_Client")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_typeclient");

                    b.HasKey("Id_Type_Client")
                        .HasName("pk_type_client");

                    b.ToTable("type_client", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Type_Equipement", b =>
                {
                    b.Property<int>("Id_Type_Equipement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Type_Equipement"));

                    b.Property<string>("Nom_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_type");

                    b.HasKey("Id_Type_Equipement")
                        .HasName("pk_type_equipement");

                    b.ToTable("type_equipement", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Type_Prestation", b =>
                {
                    b.Property<int>("Id_Type_Prestation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type_prestation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Type_Prestation"));

                    b.Property<string>("Nom_Type_Prestation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nom_type_prestation");

                    b.HasKey("Id_Type_Prestation")
                        .HasName("pk_type_prestation");

                    b.ToTable("type_prestation", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Unite", b =>
                {
                    b.Property<int>("Id_Unite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_unite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Unite"));

                    b.Property<string>("Nom_Unite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nom_unite");

                    b.HasKey("Id_Unite")
                        .HasName("pk_unite");

                    b.ToTable("unite", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Unite_Oeuvre", b =>
                {
                    b.Property<int>("Id_Unite_Oeuvre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_unite_oeuvre");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Unite_Oeuvre"));

                    b.Property<string>("Nom_Unite_Oeuvre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nom_unite_oeuvre");

                    b.HasKey("Id_Unite_Oeuvre")
                        .HasName("pk_unite_oeuvre");

                    b.ToTable("unite_oeuvre", "usmbTech");
                });

            modelBuilder.Entity("USMB_TECH.Models.Associer", b =>
                {
                    b.HasOne("USMB_TECH.Models.Contact_USMB", "Contact_USMBNavigation")
                        .WithMany("Associers")
                        .HasForeignKey("Id_Contact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_USMB_associer");

                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Associers")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pole_expertise_associer");

                    b.Navigation("Contact_USMBNavigation");

                    b.Navigation("Pole_ExpertiseNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Consommable", b =>
                {
                    b.HasOne("USMB_TECH.Models.Unite", "UniteNavigation")
                        .WithMany("Consommables")
                        .HasForeignKey("Id_Unite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unite_consommable");

                    b.Navigation("UniteNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Consommer", b =>
                {
                    b.HasOne("USMB_TECH.Models.Consommable", "ConsommableNavigation")
                        .WithMany("Consommers")
                        .HasForeignKey("Id_Consommable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consommer_consommable");

                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Consommers")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipement_consommer");

                    b.Navigation("ConsommableNavigation");

                    b.Navigation("EquipementNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Contact_USMB", b =>
                {
                    b.HasOne("USMB_TECH.Models.Fonction", "FonctionNavigation")
                        .WithMany("Contacts")
                        .HasForeignKey("Id_Fonction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fonction_contact");

                    b.HasOne("USMB_TECH.Models.Laboratoire", "LaboratoireNavigation")
                        .WithMany("Contacts")
                        .HasForeignKey("Nom_Court")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_laboratoire_contact_USMB");

                    b.Navigation("FonctionNavigation");

                    b.Navigation("LaboratoireNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Designer", b =>
                {
                    b.HasOne("USMB_TECH.Models.Mot_Clef", "Mot_ClefNavigation")
                        .WithMany("Designers")
                        .HasForeignKey("Id_Mot_Clef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mot_clef_designer");

                    b.HasOne("USMB_TECH.Models.Laboratoire", "LaboratoireNavigation")
                        .WithMany("Designers")
                        .HasForeignKey("Nom_Court")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_laboratoire_designer");

                    b.Navigation("LaboratoireNavigation");

                    b.Navigation("Mot_ClefNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Equipement", b =>
                {
                    b.HasOne("USMB_TECH.Models.Modele", "ModeleNavigation")
                        .WithMany("Equipements")
                        .HasForeignKey("Id_Modele")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modele_equipement");

                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Equipements")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pole_expertise_equipement");

                    b.HasOne("USMB_TECH.Models.Type_Equipement", "Type_EquipementNavigation")
                        .WithMany("Equipements")
                        .HasForeignKey("Id_Type_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_equipement_equipement");

                    b.Navigation("ModeleNavigation");

                    b.Navigation("Pole_ExpertiseNavigation");

                    b.Navigation("Type_EquipementNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Est_Lier", b =>
                {
                    b.HasOne("USMB_TECH.Models.Thematique", "ThematiqueNavigation")
                        .WithMany("Est_Liers")
                        .HasForeignKey("Id_Thematique")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thematique_est_lier");

                    b.HasOne("USMB_TECH.Models.Laboratoire", "LaboratoireNavigation")
                        .WithMany("Est_Liers")
                        .HasForeignKey("Nom_Court")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_laboratoire_est_lier");

                    b.Navigation("LaboratoireNavigation");

                    b.Navigation("ThematiqueNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Exemple_Utilisation", b =>
                {
                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Exemple_Utilisations")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_exemple_utilisation_equipement");

                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Exemple_Utilisations")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_pole_expertise_exemple_utilisation");

                    b.Navigation("EquipementNavigation");

                    b.Navigation("Pole_ExpertiseNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Exposer", b =>
                {
                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Exposers")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exposer_equipement");

                    b.HasOne("USMB_TECH.Models.Thematique", "ThematiqueNavigation")
                        .WithMany("Exposers")
                        .HasForeignKey("Id_Thematique")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thematique_exposer");

                    b.Navigation("EquipementNavigation");

                    b.Navigation("ThematiqueNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Fournir", b =>
                {
                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Fournirs")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fournir_equipement");

                    b.HasOne("USMB_TECH.Models.Prestation", "PrestationNavigation")
                        .WithMany("Fournirs")
                        .HasForeignKey("Id_Prestation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fournir_prestation");

                    b.Navigation("EquipementNavigation");

                    b.Navigation("PrestationNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Gerer", b =>
                {
                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Gerers")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pole_expertise_gerer");

                    b.HasOne("USMB_TECH.Models.Laboratoire", "LaboratoireNavigation")
                        .WithMany("Gerers")
                        .HasForeignKey("Nom_Court")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_laboratoire_gerer");

                    b.Navigation("LaboratoireNavigation");

                    b.Navigation("Pole_ExpertiseNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Laboratoire", b =>
                {
                    b.HasOne("USMB_TECH.Models.Adresse", "Adresse_campusNavigation")
                        .WithMany("Laboratoires_campus")
                        .HasForeignKey("Id_Adresse_Campus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_laboratoire_adresse_campus");

                    b.HasOne("USMB_TECH.Models.Adresse", "Adresse_laboNavigation")
                        .WithMany("Laboratoires_labo")
                        .HasForeignKey("Id_Adresse_Labo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_laboratoire_adresse_labo");

                    b.Navigation("Adresse_campusNavigation");

                    b.Navigation("Adresse_laboNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Modele", b =>
                {
                    b.HasOne("USMB_TECH.Models.Marque", "MarqueNavigation")
                        .WithMany("Modeles")
                        .HasForeignKey("Id_Marque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modele_marque");

                    b.Navigation("MarqueNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Photo", b =>
                {
                    b.HasOne("USMB_TECH.Models.Domaine_Excellence", "Domaine_ExcellenceNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("Id_Domaine_Excellence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_photo_domaine_excelence");

                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_photo_equipement");

                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_pole_expertise_photo");

                    b.HasOne("USMB_TECH.Models.Prestation", "PrestationNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("Id_Prestation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_prestation_photo");

                    b.HasOne("USMB_TECH.Models.Laboratoire", "LaboratoireNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("Nom_Court")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_photo_laboratoire");

                    b.Navigation("Domaine_ExcellenceNavigation");

                    b.Navigation("EquipementNavigation");

                    b.Navigation("LaboratoireNavigation");

                    b.Navigation("Pole_ExpertiseNavigation");

                    b.Navigation("PrestationNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Pole_Expertise", b =>
                {
                    b.HasOne("USMB_TECH.Models.Domaine_Excellence", "Domaine_ExcellenceNavigation")
                        .WithMany("Pole_Expertises")
                        .HasForeignKey("Id_Domaine_Excellence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_domaine_excellence_pole_expertise");

                    b.Navigation("Domaine_ExcellenceNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Posseder", b =>
                {
                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Posseders")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posseder_equipement");

                    b.HasOne("USMB_TECH.Models.Fonctionalite", "FonctionaliteNavigation")
                        .WithMany("Posseders")
                        .HasForeignKey("Id_Fonctionalite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posseder_fonctionalite");

                    b.Navigation("EquipementNavigation");

                    b.Navigation("FonctionaliteNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Preciser", b =>
                {
                    b.HasOne("USMB_TECH.Models.Mot_Clef", "Mot_ClefNavigation")
                        .WithMany("Precisers")
                        .HasForeignKey("Id_Mot_Clef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preciser_mot_clef");

                    b.HasOne("USMB_TECH.Models.Prestation", "PrestationNavigation")
                        .WithMany("Precisers")
                        .HasForeignKey("Id_Prestation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preciser_prestation");

                    b.Navigation("Mot_ClefNavigation");

                    b.Navigation("PrestationNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Presenter", b =>
                {
                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Presenters")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presenter_pole_expertise");

                    b.HasOne("USMB_TECH.Models.Prestation", "PrestationNavigation")
                        .WithMany("Presenters")
                        .HasForeignKey("Id_Prestation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presenter_prestation");

                    b.Navigation("Pole_ExpertiseNavigation");

                    b.Navigation("PrestationNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Prestation", b =>
                {
                    b.HasOne("USMB_TECH.Models.Contact_USMB", "Contact_USMBNavigation")
                        .WithMany("Prestations")
                        .HasForeignKey("Id_Contact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prestation_contact_usmb");

                    b.HasOne("USMB_TECH.Models.Domaine_Excellence", "Domaine_ExcellenceNavigation")
                        .WithMany("Prestations")
                        .HasForeignKey("Id_Domaine_Excellence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prestation_domaine_excellence");

                    b.HasOne("USMB_TECH.Models.Type_Prestation", "Type_PrestationNavigation")
                        .WithMany("Prestations")
                        .HasForeignKey("Id_Type_Prestation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_prestation_prestation");

                    b.HasOne("USMB_TECH.Models.Unite_Oeuvre", "Unite_OeuvreNavigation")
                        .WithMany("Prestations")
                        .HasForeignKey("Id_Unite_Oeuvre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unite_oeuvre_prestation");

                    b.HasOne("USMB_TECH.Models.Laboratoire", "LaboratoireNavigation")
                        .WithMany("Prestations")
                        .HasForeignKey("Nom_Court")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_prestation_laboratoire");

                    b.Navigation("Contact_USMBNavigation");

                    b.Navigation("Domaine_ExcellenceNavigation");

                    b.Navigation("LaboratoireNavigation");

                    b.Navigation("Type_PrestationNavigation");

                    b.Navigation("Unite_OeuvreNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Prise_Contact", b =>
                {
                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Prise_Contacts")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_prise_contact_equipement");

                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Prise_Contacts")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_prise_contact_pole_expertise");

                    b.HasOne("USMB_TECH.Models.Type_Client", "Type_ClientNavigation")
                        .WithMany("Prise_Contacts")
                        .HasForeignKey("Id_Type_Client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_client_prise_contact");

                    b.Navigation("EquipementNavigation");

                    b.Navigation("Pole_ExpertiseNavigation");

                    b.Navigation("Type_ClientNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Qualifier", b =>
                {
                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Qualifiers")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualifier_equipement");

                    b.HasOne("USMB_TECH.Models.Mot_Clef", "Mot_ClefNavigation")
                        .WithMany("Qualifiers")
                        .HasForeignKey("Id_Mot_Clef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualifier_mot_clef");

                    b.Navigation("EquipementNavigation");

                    b.Navigation("Mot_ClefNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Referencer", b =>
                {
                    b.HasOne("USMB_TECH.Models.Contact_USMB", "Contact_USMBNavigation")
                        .WithMany("Referencers")
                        .HasForeignKey("Id_Contact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referencer_contact");

                    b.HasOne("USMB_TECH.Models.Equipement", "EquipementNavigation")
                        .WithMany("Referencers")
                        .HasForeignKey("Id_Equipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_referencer_equipement");

                    b.Navigation("Contact_USMBNavigation");

                    b.Navigation("EquipementNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Specifier", b =>
                {
                    b.HasOne("USMB_TECH.Models.Mot_Clef", "Mot_ClefNavigation")
                        .WithMany("Specifiers")
                        .HasForeignKey("Id_Mot_Clef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specifier_mot_clef");

                    b.HasOne("USMB_TECH.Models.Pole_Expertise", "Pole_ExpertiseNavigation")
                        .WithMany("Specifiers")
                        .HasForeignKey("Id_Pole_Expertise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specifier_pole_expertise");

                    b.Navigation("Mot_ClefNavigation");

                    b.Navigation("Pole_ExpertiseNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Thematique", b =>
                {
                    b.HasOne("USMB_TECH.Models.Thematique", "ThematiqueNavigation")
                        .WithMany("Thematiques")
                        .HasForeignKey("Id_Thematique")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thematique_thematique_parente");

                    b.Navigation("ThematiqueNavigation");
                });

            modelBuilder.Entity("USMB_TECH.Models.Adresse", b =>
                {
                    b.Navigation("Laboratoires_campus");

                    b.Navigation("Laboratoires_labo");
                });

            modelBuilder.Entity("USMB_TECH.Models.Consommable", b =>
                {
                    b.Navigation("Consommers");
                });

            modelBuilder.Entity("USMB_TECH.Models.Contact_USMB", b =>
                {
                    b.Navigation("Associers");

                    b.Navigation("Prestations");

                    b.Navigation("Referencers");
                });

            modelBuilder.Entity("USMB_TECH.Models.Domaine_Excellence", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Pole_Expertises");

                    b.Navigation("Prestations");
                });

            modelBuilder.Entity("USMB_TECH.Models.Equipement", b =>
                {
                    b.Navigation("Consommers");

                    b.Navigation("Exemple_Utilisations");

                    b.Navigation("Exposers");

                    b.Navigation("Fournirs");

                    b.Navigation("Photos");

                    b.Navigation("Posseders");

                    b.Navigation("Prise_Contacts");

                    b.Navigation("Qualifiers");

                    b.Navigation("Referencers");
                });

            modelBuilder.Entity("USMB_TECH.Models.Fonction", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("USMB_TECH.Models.Fonctionalite", b =>
                {
                    b.Navigation("Posseders");
                });

            modelBuilder.Entity("USMB_TECH.Models.Laboratoire", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Designers");

                    b.Navigation("Est_Liers");

                    b.Navigation("Gerers");

                    b.Navigation("Photos");

                    b.Navigation("Prestations");
                });

            modelBuilder.Entity("USMB_TECH.Models.Marque", b =>
                {
                    b.Navigation("Modeles");
                });

            modelBuilder.Entity("USMB_TECH.Models.Modele", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("USMB_TECH.Models.Mot_Clef", b =>
                {
                    b.Navigation("Designers");

                    b.Navigation("Precisers");

                    b.Navigation("Qualifiers");

                    b.Navigation("Specifiers");
                });

            modelBuilder.Entity("USMB_TECH.Models.Pole_Expertise", b =>
                {
                    b.Navigation("Associers");

                    b.Navigation("Equipements");

                    b.Navigation("Exemple_Utilisations");

                    b.Navigation("Gerers");

                    b.Navigation("Photos");

                    b.Navigation("Presenters");

                    b.Navigation("Prise_Contacts");

                    b.Navigation("Specifiers");
                });

            modelBuilder.Entity("USMB_TECH.Models.Prestation", b =>
                {
                    b.Navigation("Fournirs");

                    b.Navigation("Photos");

                    b.Navigation("Precisers");

                    b.Navigation("Presenters");
                });

            modelBuilder.Entity("USMB_TECH.Models.Thematique", b =>
                {
                    b.Navigation("Est_Liers");

                    b.Navigation("Exposers");

                    b.Navigation("Thematiques");
                });

            modelBuilder.Entity("USMB_TECH.Models.Type_Client", b =>
                {
                    b.Navigation("Prise_Contacts");
                });

            modelBuilder.Entity("USMB_TECH.Models.Type_Equipement", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("USMB_TECH.Models.Type_Prestation", b =>
                {
                    b.Navigation("Prestations");
                });

            modelBuilder.Entity("USMB_TECH.Models.Unite", b =>
                {
                    b.Navigation("Consommables");
                });

            modelBuilder.Entity("USMB_TECH.Models.Unite_Oeuvre", b =>
                {
                    b.Navigation("Prestations");
                });
#pragma warning restore 612, 618
        }
    }
}
