name: Build and Deploy Blazor WASM to Azure Web App - blazor-usmbtech

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish Blazor
        run: dotnet publish USMB_TECH_Blazor/USMB_TECH_Blazor.csproj -c Release -o publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BD0858EFC5741B68F3AC9032383401D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32ED0014365042A496D6DFB73E074325 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E30AF12E185747C5BC16ABAF46E25716 }}

      - name: Deploy Blazor
        uses: azure/webapps-deploy@v3
        with:
          app-name: blazor-usmbtech
          slot-name: Production
          package: publish
