name: Build and deploy ASP.Net Core API + Blazor WASM to Azure Web App - api-usmbtech

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore USMB_TECH_API/USMB_TECH_API.csproj

      - name: Build solution
        run: dotnet build USMB_TECH_API/USMB_TECH_API.csproj --configuration Release --no-restore

      - name: Publish API with Blazor front-end
        run: dotnet publish USMB_TECH_API/USMB_TECH_API.csproj --configuration Release --output publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: full-app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: full-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9FD37313CE8C4F389B9976F30123971B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF49F06B2F244A3DAA092FFFDDF4DF78 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5081036E4D9E46B2ADAF49DD7A106AC6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-usmbtech'
          slot-name: 'Production'
          package: .
